import os
import asyncio
import feedparser
import random
import urllib.parse
from openai import OpenAI
from telebot.async_telebot import AsyncTeleBot

HF_KEY = os.getenv("HF_API_KEY")
TG_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TG_CHAT = os.getenv("TELEGRAM_CHAT_ID")

if not all([HF_KEY, TG_TOKEN, TG_CHAT]):
    print("❌ ОШИБКА: Не все секреты настроены.")
    exit(1)

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=HF_KEY
)
bot = AsyncTeleBot(TG_TOKEN)
MODEL_NAME = "Qwen/Qwen2.5-72B-Instruct"

async def get_news_headline():
    try:
        feed = await asyncio.to_thread(feedparser.parse, "https://habr.com/ru/rss/articles/?fl=ru")
        if not feed.entries:
            return None
        top_entries = feed.entries[:5]
        return random.choice(top_entries).title
    except Exception as e:
        print(f"Ошибка парсинга: {e}")
        return None

async def generate_meme_concept(headline):
    system_prompt = (
        "Ты — 40-летний токсичный арт-директор рекламного агентства. Ты выгорел, "
        "ненавидишь зумеров и сарказм — твой второй язык. Тебе приносят новость, "
        "а ты должен придумать из неё смешной, постироничный мем. "
        "Опиши, что должно быть на картинке, и какой текст (панчлайн) добавить. "
        "Верни ответ СТРОГО в формате: "
        "ПРОМПТ: <описание картинки на английском для нейросети (максимум 50 слов)>\n"
        "ТЕКСТ: <короткий панчлайн на русском>"
    )
    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Новость: {headline}"}
            ],
            temperature=0.8
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Ошибка ИИ: {e}")
        return None

async def send_to_telegram(image_url, caption_text):
    try:
        await bot.send_photo(TG_CHAT, image_url, caption=caption_text, parse_mode='HTML')
        print("✅ Успешно опубликовано!")
    except Exception as e:
        print(f"Ошибка Telegram: {e}")

async def run_factory_once():
    headline = await get_news_headline()
    if not headline:
        return
    print(f"📰 Найдено: {headline}\n")

    concept_raw = await generate_meme_concept(headline)
    if not concept_raw:
        return
    print(f"🚬 Арт-директор:\n{concept_raw}\n")

    img_prompt = None
    caption_text = f"📰 <b>{headline}</b>\n\nGenerated by MemeFactory"

    for line in concept_raw.split("\n"):
        if line.startswith("ПРОМПТ:"):
            img_prompt = line.replace("ПРОМПТ:", "").strip()
        if line.startswith("ТЕКСТ:"):
            text = line.replace("ТЕКСТ:", "").strip()
            caption_text = f"📰 <b>{headline}</b>\n\n<blockquote>{text}</blockquote>"

    if not img_prompt:
        print("❌ Не удалось спарсить промпт.")
        return

    encoded_img_prompt = urllib.parse.quote(img_prompt)
    image_url = f"https://image.pollinations.ai/prompt/{encoded_img_prompt}?width=1024&height=1024&nologo=true&private=true&enhance=false"

    await send_to_telegram(image_url, caption_text)

if __name__ == "__main__":
    asyncio.run(run_factory_once())
